---
title: "Analisis exploratorio datos"
author: "Felipe Tucca"
date: '2022-05-03'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(stats)
library(MASS)
library(Rlab)
library(ggplot2)
library(psych)
library(kableExtra)
library(knitr)
library(DT)
library(pander)
library(tidyverse)
library(dplyr)
library(tidyr)

```

## **Análisis exploratorio de datos**

# Descripción de variables de estudio mediante histograma

```{r resumen, echo=TRUE}
summary(Mortalidad)
```

```{r transformación datos, echo=FALSE}
Mortalidad$centro_id <- as.factor(Mortalidad$centro_id)
Mortalidad$año <- as.factor(Mortalidad$año)
Mortalidad$mes <- as.factor(Mortalidad$mes)
Mortalidad$Semana <- as.factor(Mortalidad$Semana)
```

```{r resumen con factores modificados, echo=TRUE}
summary(Mortalidad)
```

```{r ordenar datos con gather, echo=TRUE}
Mortalidad %>% gather("Mort_bloom", "Mort_OD", 7:8 )
```

```{r resumen, echo=FALSE}
summary(Mortalidad)
```



## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
